Repository aliya-rahmani/Hacktoberfest-Projects, pull requests merged in 2020-11, with the labels that each got.

#481 Add Gaussian elimination method
  gaussian.py
Labels: hacktoberfest-accepted

#506 Create ShellSort.java
  Java/ShellSort.java
Labels: hacktoberfest-accepted

#505 Create 1D_Array_In_C
  C/1D_Array_In_C
Labels: hacktoberfest-accepted

#503 Complex Numbers program in java
  Java/Complex_Number.java
Labels: hacktoberfest-accepted

#502 Create Egg_dropping_puzzle_dp.cpp
  C++/DynamicProgramming/Egg_dropping_puzzle_dp.cpp
Labels: hacktoberfest-accepted

#501 minimumsumoffactors.py
  betweentwosetsthecommonfactors.py
  minimumsumoffactors.py
Labels: hacktoberfest-accepted

#500 Create Longest_Palindromic_Substring.cpp
  C++/DynamicProgramming/Longest_Palindromic_Substring.cpp
Labels: hacktoberfest-accepted

#494 Create Second_Largest_Element_In_A_1D_array
  C++/Second_Largest_Element_In_A_1D_array
Labels: hacktoberfest-accepted

#504 Create RandomPasswordGenerator.c
  RandomPasswordGenerator.c
Labels: hacktoberfest-accepted

#489 Create coinflip.py
  Python/coinflip.py
Labels: hacktoberfest-accepted

#488 Create binomial_distribution.py
  Python/binomial_distribution.py
Labels: hacktoberfest-accepted

#487 Create LongestConsecutiveSubstring.py
  Python/LongestConsecutiveSubstring.py
Labels: hacktoberfest-accepted

#486 Create multiplication_table.py
  Python/multiplication_table.py
Labels: hacktoberfest-accepted

#483 Create Linear searching
  Linear searching
Labels: hacktoberfest-accepted

#484 Create prime.py
  Python/prime.py
Labels: hacktoberfest-accepted

#485 Create vowels.py
  Python/vowels.py
Labels: hacktoberfest-accepted

#482 Create dice_roller
  Python/dice_roller
Labels: hacktoberfest-accepted

#124 test file
  myfirst file
Labels: question

#93 HTML Page for Registration. Frontend and Backend
  suma_class3.rar
Labels: invalid
